In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
from keras.utils import np_utils
np.random.seed(10)
from keras.datasets import mnist
import matplotlib.pyplot as plt
from keras.layers import Conv2D,MaxPooling2D,Dropout,Flatten,Dense
from keras.utils import np_utils
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Activation, Flatten, LSTM, TimeDistributed, RepeatVector,Input
from keras.optimizers import adam_v2
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
from keras.models import Sequential
nor=1

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!unzip /content/drive/MyDrive/colab/pic_500.zip

Archive:  /content/drive/MyDrive/colab/pic_500.zip
   creating: pic_500/
   creating: pic_500/lay/
  inflating: pic_500/lay/lay0.jpg    
  inflating: pic_500/lay/lay1.jpg    
  inflating: pic_500/lay/lay10.jpg   
  inflating: pic_500/lay/lay100.jpg  
  inflating: pic_500/lay/lay101.jpg  
  inflating: pic_500/lay/lay102.jpg  
  inflating: pic_500/lay/lay103.jpg  
  inflating: pic_500/lay/lay104.jpg  
  inflating: pic_500/lay/lay105.jpg  
  inflating: pic_500/lay/lay106.jpg  
  inflating: pic_500/lay/lay107.jpg  
  inflating: pic_500/lay/lay108.jpg  
  inflating: pic_500/lay/lay109.jpg  
  inflating: pic_500/lay/lay11.jpg   
  inflating: pic_500/lay/lay110.jpg  
  inflating: pic_500/lay/lay111.jpg  
  inflating: pic_500/lay/lay112.jpg  
  inflating: pic_500/lay/lay113.jpg  
  inflating: pic_500/lay/lay114.jpg  
  inflating: pic_500/lay/lay115.jpg  
  inflating: pic_500/lay/lay116.jpg  
  inflating: pic_500/lay/lay117.jpg  
  inflating: pic_500/lay/lay118.jpg  
  inflating: pic_500/lay/la

In [ ]:
!unzip /content/drive/MyDrive/colab/pic.zip

Archive:  /content/drive/MyDrive/colab/pic.zip
   creating: pic/
   creating: pic/lay/
 extracting: pic/lay/lay0.png        
 extracting: pic/lay/lay1.png        
 extracting: pic/lay/lay10.png       
 extracting: pic/lay/lay11.png       
 extracting: pic/lay/lay12.png       
 extracting: pic/lay/lay13.png       
 extracting: pic/lay/lay14.png       
 extracting: pic/lay/lay15.png       
 extracting: pic/lay/lay16.png       
 extracting: pic/lay/lay17.png       
 extracting: pic/lay/lay18.png       
 extracting: pic/lay/lay19.png       
 extracting: pic/lay/lay2.png        
 extracting: pic/lay/lay20.png       
 extracting: pic/lay/lay21.png       
 extracting: pic/lay/lay22.png       
 extracting: pic/lay/lay23.png       
 extracting: pic/lay/lay24.png       
 extracting: pic/lay/lay25.png       
 extracting: pic/lay/lay26.png       
 extracting: pic/lay/lay27.png       
 extracting: pic/lay/lay28.png       
 extracting: pic/lay/lay29.png       
 extracting: pic/lay/lay3.png        
 

In [ ]:
from PIL import Image
import numpy as np
cnt = 0
j=0
jj=45
im = Image.open("pic/lay/lay"+str(j)+".png")
im_se = im.getdata()
im_ar=np.array(im_se)
train_feature=np.array([im_ar/nor])
train_label = np.array([0])
for z in range(j+1,jj):
  im = Image.open("pic/lay/lay"+str(z)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [0], axis=0)    

im = Image.open("pic/sit/sit"+str(j)+".png")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [1], axis=0) 
for z in range(j+1,jj):
  im = Image.open("pic/sit/sit"+str(z)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [1], axis=0)  

im = Image.open("pic/lean/lean"+str(j)+".png")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [2], axis=0) 
for z in range(j+1,jj):
  if z!= 6:
    im = Image.open("pic/lean/lean"+str(z)+".png")
    im_se = im.getdata()
    im_ar=np.array(im_se)
    temp=np.array([im_ar/nor])  
    train_feature=np.append(train_feature, temp, axis=0) 
    train_label=np.append(train_label, [2], axis=0)  

train_feature_vector = train_feature.reshape(len(train_feature), 640,480,1).astype('float32')
train_label_onehot = np_utils.to_categorical(train_label)


FileNotFoundError: ignored

In [ ]:
from PIL import Image
import numpy as np
cnt = 0
j=0
jj=45
for z in range(j,jj):
  im = Image.open("pic_500/lay/lay"+str(j)+".jpg")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [0], axis=0)    

im = Image.open("pic_500/sit/sit"+str(j)+".jpg")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [1], axis=0) 
for z in range(j+1,jj):
  im = Image.open("pic_500/sit/sit"+str(z)+".jpg")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [1], axis=0)  

im = Image.open("pic_500/lean/lean"+str(j)+".jpg")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [2], axis=0) 
for z in range(j+1,jj):
  if z!= 6:
    im = Image.open("pic_500/lean/lean"+str(z)+".jpg")
    im_se = im.getdata()
    im_ar=np.array(im_se)
    temp=np.array([im_ar/nor])  
    train_feature=np.append(train_feature, temp, axis=0) 
    train_label=np.append(train_label, [2], axis=0)  

train_feature_vector = train_feature.reshape(len(train_feature), 640,480,1).astype('float32')
train_label_onehot = np_utils.to_categorical(train_label)


In [ ]:
model = Sequential()


model.add(Conv2D(filters=15, 
                 kernel_size=(3,3),
                 padding='same',
                 input_shape=(640,480,1), 
                 activation='relu'))
model.add(MaxPooling2D(pool_size=(100, 100)))
model.add(Flatten()) 

model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=3,activation='softmax'))
adam = adam_v2.Adam(lr=0.0001, beta_1=0.99, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
model.compile(loss='categorical_crossentropy', 
              optimizer=adam, metrics=['accuracy'])

train_history =model.fit(x=train_feature_vector,
                         y=train_label_onehot,validation_split=0, 
                         epochs=20, batch_size=5,verbose=2)
model.save('a.h5')
model.summary()
"""
scores = model.evaluate(test_feature_vector, test_label_onehot)
print(model.predict(test_feature_vector))
print(test_label_onehot)
print('\n準確率=',scores[1])
model.save('a.h5')
"""

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/20


ValueError: ignored

In [ ]:
c=50

for j in range(45,51):
  print("index ="+str(j))
  im = Image.open("pic/lay/lay"+str(j)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  test_feature=np.array([im_ar/nor])
  test_label = np.array([0])
  test_label_onehot = np_utils.to_categorical(test_label)
  test_feature_vector = test_feature.reshape(len(test_feature), 640,480,1).astype('float32')
  print(model.predict(test_feature_vector))
  im = Image.open("pic/sit/sit"+str(j)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  test_feature=np.array([im_ar/nor])
  test_label = np.array([1])
  test_label_onehot = np_utils.to_categorical(test_label)
  test_feature_vector = test_feature.reshape(len(test_feature), 640,480,1).astype('float32')
  print(model.predict(test_feature_vector))
  im = Image.open("pic/lean/lean"+str(j)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  test_feature=np.array([im_ar/nor])
  test_label = np.array([2])
  test_label_onehot = np_utils.to_categorical(test_label)
  test_feature_vector = test_feature.reshape(len(test_feature), 640,480,1).astype('float32')
  print(model.predict(test_feature_vector))


index =45
[[0.07873226 0.92126775]]
[[0.59222037 0.40777966]]
[[0.22707106 0.77292895]]
index =46
[[0.07451577 0.9254842 ]]
[[0.779986   0.22001398]]
[[0.262526   0.73747396]]
index =47
[[0.08374333 0.9162566 ]]
[[0.681266   0.31873402]]
[[0.2042963  0.79570365]]
index =48
[[0.10698398 0.893016  ]]
[[0.76529443 0.2347056 ]]
[[0.15485418 0.8451458 ]]
index =49
[[0.07369549 0.9263045 ]]
[[0.5245469 0.4754531]]
[[0.556538 0.443462]]
index =50
[[0.08775788 0.9122421 ]]
[[0.69171625 0.3082838 ]]
[[0.20998052 0.79001945]]


In [ ]:
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
converter.inference_input_type, converter.inference_output_type

INFO:tensorflow:Assets written to: /tmp/tmp34wcwa15/assets


INFO:tensorflow:Assets written to: /tmp/tmp34wcwa15/assets


(tf.float32, tf.float32)

In [ ]:
import pathlib

generated_dir = pathlib.Path("/content/drive/MyDrive/colab/")
generated_dir.mkdir(exist_ok=True, parents=True)
converted_model_file = generated_dir/"emb_fi.tflite"
converted_model_file.write_bytes(tflite_model)  

232720