In [1]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
from keras.utils import np_utils
np.random.seed(10)
from keras.datasets import mnist
import matplotlib.pyplot as plt
from keras.layers import Conv2D,MaxPooling2D,Dropout,Flatten,Dense
from keras.utils import np_utils
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Activation, Flatten, LSTM, TimeDistributed, RepeatVector,Input
from keras.optimizers import adam_v2
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
from keras.models import Sequential
import tensorflow as tf
nor=1

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
print(tf.__version__)

2.8.2


In [2]:
!unzip /content/drive/MyDrive/colab/pic_96.zip

Archive:  /content/drive/MyDrive/colab/pic_96.zip
   creating: pic_96/
   creating: pic_96/lay/
 extracting: pic_96/lay/lay0.jpg     
 extracting: pic_96/lay/lay1.jpg     
 extracting: pic_96/lay/lay10.jpg    
 extracting: pic_96/lay/lay100.jpg   
 extracting: pic_96/lay/lay101.jpg   
 extracting: pic_96/lay/lay102.jpg   
 extracting: pic_96/lay/lay103.jpg   
 extracting: pic_96/lay/lay104.jpg   
 extracting: pic_96/lay/lay105.jpg   
 extracting: pic_96/lay/lay106.jpg   
 extracting: pic_96/lay/lay107.jpg   
 extracting: pic_96/lay/lay108.jpg   
 extracting: pic_96/lay/lay109.jpg   
 extracting: pic_96/lay/lay11.jpg    
 extracting: pic_96/lay/lay110.jpg   
 extracting: pic_96/lay/lay111.jpg   
 extracting: pic_96/lay/lay112.jpg   
 extracting: pic_96/lay/lay113.jpg   
 extracting: pic_96/lay/lay114.jpg   
 extracting: pic_96/lay/lay115.jpg   
 extracting: pic_96/lay/lay116.jpg   
 extracting: pic_96/lay/lay117.jpg   
 extracting: pic_96/lay/lay118.jpg   
 extracting: pic_96/lay/lay119

In [3]:
from PIL import Image
import numpy as np
cnt = 0
j=10
jj=500
im = Image.open("pic_96/lay/lay"+str(j)+".jpg")
im_se = im.getdata()
im_ar=np.array(im_se)
train_feature=np.array([im_ar/nor])
train_label = np.array([0])
for z in range(j+1,jj):
  im = Image.open("pic_96/lay/lay"+str(z)+".jpg")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [0], axis=0)    

im = Image.open("pic_96/sit/sit"+str(j)+".jpg")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [1], axis=0) 
for z in range(j+1,jj):
  im = Image.open("pic_96/sit/sit"+str(z)+".jpg")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [1], axis=0)  

im = Image.open("pic_96/lean/lean"+str(j)+".jpg")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [2], axis=0) 
for z in range(j+1,jj):
  if z!= 6:
    im = Image.open("pic_96/lean/lean"+str(z)+".jpg")
    im_se = im.getdata()
    im_ar=np.array(im_se)
    temp=np.array([im_ar/nor])  
    train_feature=np.append(train_feature, temp, axis=0) 
    train_label=np.append(train_label, [2], axis=0)  

#train_feature=np.where(train_feature<210.0,0,128)
#train_feature=(train_feature-128)
#train_feature=train_feature-128
train_feature_vector = train_feature.reshape(len(train_feature), 96,96,1).astype('float32')
train_label_onehot = np_utils.to_categorical(train_label)


In [6]:
model = Sequential()

model.add(Conv2D(filters=10, 
                 kernel_size=(5,5),
                 padding='same',
                 input_shape=(96,96,1), 
                 activation='relu'))
model.add(MaxPooling2D(pool_size=(3, 3)))
model.add(Conv2D(filters=10, 
                 kernel_size=(3,3),
                 padding='same',
                 input_shape=(30,30,1), 
                 activation='relu'))
model.add(MaxPooling2D(pool_size=(5, 5)))
model.add(Flatten()) 

model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=3,activation='softmax'))
adam = adam_v2.Adam(lr=0.001, beta_1=0.99, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
model.compile(loss='categorical_crossentropy', 
              optimizer=adam, metrics=['accuracy'])

train_history =model.fit(x=train_feature_vector,
                         y=train_label_onehot,validation_split=0.2, 
                         epochs=10, batch_size=5,verbose=2)
model.save('a.h5')
model.summary()
"""
scores = model.evaluate(test_feature_vector, test_label_onehot)
print(model.predict(test_feature_vector))
print(test_label_onehot)
print('\n準確率=',scores[1])
model.save('a.h5')
"""

Epoch 1/10


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


236/236 - 2s - loss: 1.4483 - accuracy: 0.6233 - val_loss: 1.5209 - val_accuracy: 0.0000e+00 - 2s/epoch - 9ms/step
Epoch 2/10
236/236 - 1s - loss: 0.4353 - accuracy: 0.8180 - val_loss: 0.9399 - val_accuracy: 0.3707 - 844ms/epoch - 4ms/step
Epoch 3/10
236/236 - 1s - loss: 0.2170 - accuracy: 0.9090 - val_loss: 0.1557 - val_accuracy: 0.9592 - 885ms/epoch - 4ms/step
Epoch 4/10
236/236 - 1s - loss: 0.1354 - accuracy: 0.9447 - val_loss: 0.9163 - val_accuracy: 0.6837 - 870ms/epoch - 4ms/step
Epoch 5/10
236/236 - 1s - loss: 0.1318 - accuracy: 0.9447 - val_loss: 0.1641 - val_accuracy: 0.9354 - 885ms/epoch - 4ms/step
Epoch 6/10
236/236 - 1s - loss: 0.1138 - accuracy: 0.9524 - val_loss: 0.4861 - val_accuracy: 0.7959 - 861ms/epoch - 4ms/step
Epoch 7/10
236/236 - 1s - loss: 0.0748 - accuracy: 0.9753 - val_loss: 0.0490 - val_accuracy: 0.9898 - 849ms/epoch - 4ms/step
Epoch 8/10
236/236 - 1s - loss: 0.0788 - accuracy: 0.9762 - val_loss: 0.0534 - val_accuracy: 0.9864 - 886ms/epoch - 4ms/step
Epoch 9/10

"\nscores = model.evaluate(test_feature_vector, test_label_onehot)\nprint(model.predict(test_feature_vector))\nprint(test_label_onehot)\nprint('\n準確率=',scores[1])\nmodel.save('a.h5')\n"

In [7]:
c=50

#train_feature=np.where(train_feature<210.0,0,255)
#train_feature=(train_feature-128)
for j in range(1,10):
  print("index ="+str(j))
  im = Image.open("pic_96/lay/lay"+str(j)+".jpg")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  test_feature=np.array([im_ar/nor])
  test_label = np.array([0])
  #train_feature=np.where(train_feature<210.0,0,255)
  #train_feature=(train_feature-128)
  test_label_onehot = np_utils.to_categorical(test_label)
  test_feature_vector = test_feature.reshape(len(test_feature), 96,96,1).astype('float32')
  print(model.predict(test_feature_vector))
  im = Image.open("pic_96/sit/sit"+str(j)+".jpg")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  test_feature=np.array([im_ar/nor])
  test_label = np.array([1])
 # train_feature=np.where(train_feature<210.0,0,255)
 #train_feature=(train_feature-128)
  test_label_onehot = np_utils.to_categorical(test_label)
  test_feature_vector = test_feature.reshape(len(test_feature), 96,96,1).astype('float32')
  print(model.predict(test_feature_vector))
  im = Image.open("pic_96/lean/lean"+str(j)+".jpg")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  test_feature=np.array([im_ar/nor])
  test_label = np.array([2])
  #train_feature=np.where(train_feature<210.0,0,255)
  #train_feature=(train_feature-128)
  test_label_onehot = np_utils.to_categorical(test_label)
  test_feature_vector = test_feature.reshape(len(test_feature), 96,96,1).astype('float32')
  print(model.predict(test_feature_vector))


index =1
[[0.5005242 0.2310502 0.2684256]]
[[0.3362685 0.3662181 0.2975133]]
[[3.9604753e-10 3.1562976e-07 9.9999964e-01]]
index =2
[[0.96851885 0.0043892  0.02709194]]
[[0.01372198 0.96942085 0.01685723]]
[[0.4973545  0.09985153 0.40279388]]
index =3
[[0.9880212  0.00123929 0.01073948]]
[[1.8752362e-03 9.9764013e-01 4.8466629e-04]]
[[0.03271063 0.07053272 0.89675665]]
index =4
[[0.66775084 0.13703203 0.19521712]]
[[0.8581461  0.02716632 0.11468762]]
[[4.1165267e-04 4.7145383e-03 9.9487382e-01]]
index =5
[[0.97701436 0.00264989 0.02033579]]
[[0.0089987  0.9888572  0.00214413]]
[[0.0316583  0.07776861 0.8905731 ]]
index =6
[[0.81630564 0.06100738 0.122687  ]]
[[2.2322915e-03 9.9723214e-01 5.3551368e-04]]
[[0.02613661 0.04871557 0.92514783]]
index =7
[[0.9870271  0.00121636 0.01175647]]
[[1.4596668e-03 9.9810177e-01 4.3857878e-04]]
[[0.08569875 0.05651949 0.85778177]]
index =8
[[0.52308893 0.33527082 0.14164019]]
[[0.00495353 0.01709975 0.97794676]]
[[0.01807524 0.5588598  0.42306495]]
i

In [8]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
converter.inference_input_type, converter.inference_output_type

INFO:tensorflow:Assets written to: /tmp/tmp747ncujh/assets


(tf.float32, tf.float32)

In [9]:
import pathlib

generated_dir = pathlib.Path("/content/drive/MyDrive/colab/")
generated_dir.mkdir(exist_ok=True, parents=True)
converted_model_file = generated_dir/"emb_fi.tflite"
converted_model_file.write_bytes(tflite_model)  

112400

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2
