In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
from keras.utils import np_utils
np.random.seed(10)
from keras.datasets import mnist
import matplotlib.pyplot as plt
from keras.layers import Conv2D,MaxPooling2D,Dropout,Flatten,Dense
from keras.utils import np_utils
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Activation, Flatten, LSTM, TimeDistributed, RepeatVector,Input
from keras.optimizers import adam_v2
from keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
from keras.models import Sequential
nor=1

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!unzip /content/drive/MyDrive/colab/pic_500.zip

Archive:  /content/drive/MyDrive/colab/pic_500.zip
replace pic_500/lay/lay0.jpg? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: pic_500/lay/lay0.jpg    
 extracting: pic_500/lay/lay1.jpg    
 extracting: pic_500/lay/lay10.jpg   
  inflating: pic_500/lay/lay100.jpg  
 extracting: pic_500/lay/lay101.jpg  
  inflating: pic_500/lay/lay102.jpg  
 extracting: pic_500/lay/lay103.jpg  
 extracting: pic_500/lay/lay104.jpg  
 extracting: pic_500/lay/lay105.jpg  
 extracting: pic_500/lay/lay106.jpg  
 extracting: pic_500/lay/lay107.jpg  
  inflating: pic_500/lay/lay108.jpg  
  inflating: pic_500/lay/lay109.jpg  
 extracting: pic_500/lay/lay11.jpg   
  inflating: pic_500/lay/lay110.jpg  
  inflating: pic_500/lay/lay111.jpg  
 extracting: pic_500/lay/lay112.jpg  
 extracting: pic_500/lay/lay113.jpg  
  inflating: pic_500/lay/lay114.jpg  
  inflating: pic_500/lay/lay115.jpg  
 extracting: pic_500/lay/lay116.jpg  
  inflating: pic_500/lay/lay117.jpg  
  inflating: pic_500/lay/lay118.jpg  
 extr

In [ ]:
!unzip /content/drive/MyDrive/colab/pic.zip

Archive:  /content/drive/MyDrive/colab/pic.zip
replace pic/lay/lay0.png? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
 extracting: pic/lay/lay0.png        
 extracting: pic/lay/lay1.png        
 extracting: pic/lay/lay10.png       
 extracting: pic/lay/lay11.png       
 extracting: pic/lay/lay12.png       
 extracting: pic/lay/lay13.png       
 extracting: pic/lay/lay14.png       
 extracting: pic/lay/lay15.png       
 extracting: pic/lay/lay16.png       
 extracting: pic/lay/lay17.png       
 extracting: pic/lay/lay18.png       
 extracting: pic/lay/lay19.png       
 extracting: pic/lay/lay2.png        
 extracting: pic/lay/lay20.png       
 extracting: pic/lay/lay21.png       
 extracting: pic/lay/lay22.png       
 extracting: pic/lay/lay23.png       
 extracting: pic/lay/lay24.png       
 extracting: pic/lay/lay25.png       
 extracting: pic/lay/lay26.png       
 extracting: pic/lay/lay27.png       
 extracting: pic/lay/lay28.png       
 extracting: pic/lay/lay29.png       
 extracting: 

In [ ]:
from PIL import Image
import numpy as np
cnt = 0
j=0
jj=45
im = Image.open("pic/lay/lay"+str(j)+".png")
im_se = im.getdata()
im_ar=np.array(im_se)
train_feature=np.array([im_ar/nor])
train_label = np.array([0])
for z in range(j+1,jj):
  im = Image.open("pic/lay/lay"+str(z)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [0], axis=0)    

im = Image.open("pic/sit/sit"+str(j)+".png")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [1], axis=0) 
for z in range(j+1,jj):
  im = Image.open("pic/sit/sit"+str(z)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [1], axis=0)  

im = Image.open("pic/lean/lean"+str(j)+".png")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [2], axis=0) 
for z in range(j+1,jj):
  if z!= 6:
    im = Image.open("pic/lean/lean"+str(z)+".png")
    im_se = im.getdata()
    im_ar=np.array(im_se)
    temp=np.array([im_ar/nor])  
    train_feature=np.append(train_feature, temp, axis=0) 
    train_label=np.append(train_label, [2], axis=0)  

train_feature_vector = train_feature.reshape(len(train_feature), 96,96,1).astype('float32')
train_label_onehot = np_utils.to_categorical(train_label)


In [ ]:
from PIL import Image
import numpy as np
cnt = 0
j=0
jj=45
for z in range(j,jj):
  im = Image.open("pic_500/lay/lay"+str(j)+".jpg")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [0], axis=0)    

im = Image.open("pic_500/sit/sit"+str(j)+".jpg")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [1], axis=0) 
for z in range(j+1,jj):
  im = Image.open("pic_500/sit/sit"+str(z)+".jpg")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  temp=np.array([im_ar/nor])  
  train_feature=np.append(train_feature, temp, axis=0) 
  train_label=np.append(train_label, [1], axis=0)  

im = Image.open("pic_500/lean/lean"+str(j)+".jpg")
im_se = im.getdata()
im_ar=np.array(im_se)
temp=np.array([im_ar/nor])
train_feature=np.append(train_feature, temp, axis=0) 
train_label=np.append(train_label, [2], axis=0) 
for z in range(j+1,jj):
  if z!= 6:
    im = Image.open("pic_500/lean/lean"+str(z)+".jpg")
    im_se = im.getdata()
    im_ar=np.array(im_se)
    temp=np.array([im_ar/nor])  
    train_feature=np.append(train_feature, temp, axis=0) 
    train_label=np.append(train_label, [2], axis=0)  

train_feature_vector = train_feature.reshape(len(train_feature), 96,96,1).astype('float32')
train_label_onehot = np_utils.to_categorical(train_label)


In [ ]:
model = Sequential()


model.add(Conv2D(filters=15, 
                 kernel_size=(3,3),
                 padding='same',
                 input_shape=(96,96,1), 
                 activation='relu'))
model.add(MaxPooling2D(pool_size=(30, 30)))
model.add(Flatten()) 

model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=3,activation='softmax'))
adam = adam_v2.Adam(lr=0.0001, beta_1=0.99, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
model.compile(loss='categorical_crossentropy', 
              optimizer=adam, metrics=['accuracy'])

train_history =model.fit(x=train_feature_vector,
                         y=train_label_onehot,validation_split=0, 
                         epochs=20, batch_size=5,verbose=2)
model.save('a.h5')
model.summary()
"""
scores = model.evaluate(test_feature_vector, test_label_onehot)
print(model.predict(test_feature_vector))
print(test_label_onehot)
print('\n準確率=',scores[1])
model.save('a.h5')
"""

Epoch 1/20


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


54/54 - 1s - loss: 2.2226 - accuracy: 0.4925 - 574ms/epoch - 11ms/step
Epoch 2/20
54/54 - 0s - loss: 0.8497 - accuracy: 0.5933 - 142ms/epoch - 3ms/step
Epoch 3/20
54/54 - 0s - loss: 0.6793 - accuracy: 0.6716 - 147ms/epoch - 3ms/step
Epoch 4/20
54/54 - 0s - loss: 0.5486 - accuracy: 0.7799 - 151ms/epoch - 3ms/step
Epoch 5/20
54/54 - 0s - loss: 0.4514 - accuracy: 0.8209 - 137ms/epoch - 3ms/step
Epoch 6/20
54/54 - 0s - loss: 0.3921 - accuracy: 0.8694 - 137ms/epoch - 3ms/step
Epoch 7/20
54/54 - 0s - loss: 0.3360 - accuracy: 0.8918 - 145ms/epoch - 3ms/step
Epoch 8/20
54/54 - 0s - loss: 0.2939 - accuracy: 0.9030 - 150ms/epoch - 3ms/step
Epoch 9/20
54/54 - 0s - loss: 0.2706 - accuracy: 0.9142 - 138ms/epoch - 3ms/step
Epoch 10/20
54/54 - 0s - loss: 0.2552 - accuracy: 0.9216 - 150ms/epoch - 3ms/step
Epoch 11/20
54/54 - 0s - loss: 0.2335 - accuracy: 0.9254 - 175ms/epoch - 3ms/step
Epoch 12/20
54/54 - 0s - loss: 0.2216 - accuracy: 0.9328 - 141ms/epoch - 3ms/step
Epoch 13/20
54/54 - 0s - loss: 0.19

"\nscores = model.evaluate(test_feature_vector, test_label_onehot)\nprint(model.predict(test_feature_vector))\nprint(test_label_onehot)\nprint('\n準確率=',scores[1])\nmodel.save('a.h5')\n"

In [ ]:
c=50

for j in range(44,50):
  print("index ="+str(j))
  im = Image.open("pic/lay/lay"+str(j)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  test_feature=np.array([im_ar/nor])
  test_label = np.array([0])
  test_label_onehot = np_utils.to_categorical(test_label)
  test_feature_vector = test_feature.reshape(len(test_feature), 96,96,1).astype('float32')
  print(model.predict(test_feature_vector))
  im = Image.open("pic/sit/sit"+str(j)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  test_feature=np.array([im_ar/nor])
  test_label = np.array([1])
  test_label_onehot = np_utils.to_categorical(test_label)
  test_feature_vector = test_feature.reshape(len(test_feature), 96,96,1).astype('float32')
  print(model.predict(test_feature_vector))
  im = Image.open("pic/lean/lean"+str(j)+".png")
  im_se = im.getdata()
  im_ar=np.array(im_se)
  test_feature=np.array([im_ar/nor])
  test_label = np.array([2])
  test_label_onehot = np_utils.to_categorical(test_label)
  test_feature_vector = test_feature.reshape(len(test_feature), 96,96,1).astype('float32')
  print(model.predict(test_feature_vector))


index =44
[[0.9815685  0.00590286 0.01252863]]
[[0.00928107 0.4731867  0.5175322 ]]
[[0.00085302 0.6071453  0.39200166]]
index =45
[[0.8973909  0.09979157 0.00281759]]
[[0.36244953 0.607822   0.02972844]]
[[0.00318751 0.6671697  0.32964283]]
index =46
[[0.97354    0.00764513 0.01881483]]
[[0.00496728 0.7472831  0.24774958]]
[[0.01750833 0.2856437  0.696848  ]]
index =47
[[0.97667277 0.02227161 0.00105567]]
[[0.823703   0.1646623  0.01163465]]
[[1.2880978e-01 7.4481941e-04 8.7044543e-01]]
index =48
[[0.9161883  0.03372582 0.05008589]]
[[0.8053755  0.15624863 0.03837581]]
[[0.06785364 0.00648686 0.92565954]]
index =49
[[0.9743765  0.01726777 0.00835567]]
[[0.92318505 0.03667852 0.04013634]]
[[0.23317659 0.00161982 0.7652036 ]]


In [ ]:
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
converter.inference_input_type, converter.inference_output_type

INFO:tensorflow:Assets written to: /tmp/tmpbl_drr0m/assets


INFO:tensorflow:Assets written to: /tmp/tmpbl_drr0m/assets


(tf.float32, tf.float32)

In [ ]:
import pathlib

generated_dir = pathlib.Path("/content/drive/MyDrive/colab/")
generated_dir.mkdir(exist_ok=True, parents=True)
converted_model_file = generated_dir/"emb_fi.tflite"
converted_model_file.write_bytes(tflite_model)  

117516